#!/bin/bash
#
# keskkonna ja oma muutujate kasutamine
# kasutame keskkonnamuutuja nimega user $USER
# tervitame kasutaja
echo "Tere, $USER!"
# kuupäeva väärtuse loomine
# defineerime vastava väärtusega muutuja
kuupaev=`date +'%d. %B'` 
#väljastame muutuja koos seletusega
echo "Täna on $kuupaev"
# kella väärtuse loomine
# defineerime vastava väärtusega muutuja
kell=`date +%H:%M`
# väljastame kell koos seletusega
echo "Kell on $kell"
kalender=`cal`
echo "Antud kuu kalender:"
echo "----------------------"
echo "$kalender"
echo "----------------------"
